const rooms = [
  {
    id: 1,
    roomName: "House Astina",
    imageUrl: "1.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 1,
    bathRoom: 1,
    period: "Year",
  },
  {
    id: 2,
    roomName: "House Astina",
    imageUrl: "2.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 1,
    bathRoom: 1,
    period: "Year",
  },
  {
    id: 3,
    roomName: "House Astina",
    imageUrl: "3.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 2,
    bathRoom: 2,
    period: "Year",
  },
  {
    id: 4,
    roomName: "House Astina",
    imageUrl: "4.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 2,
    bathRoom: 2,
    period: "Year",
  },
  {
    id: 5,
    roomName: "House Astina",
    imageUrl: "5.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 3,
    bathRoom: 3,
    period: "Year",
  },
  {
    id: 6,
    roomName: "House Astina",
    imageUrl: "6.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 3,
    bathRoom: 3,
    period: "Year",
  },
  {
    id: 7,
    roomName: "House Astina",
    imageUrl: "7.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 4,
    bathRoom: 4,
    period: "Year",
  },
  {
    id: 8,
    roomName: "House Astina",
    imageUrl: "8.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 5,
    bathRoom: 5,
    period: "Year",
  },
  {
    id: 9,
    roomName: "House Astina",
    imageUrl: "9.png",
    roomStreetAddress: "Jl. Elang IV Perum Permata Bintaro Residence",
    districtAddress: "Pondok Aren",
    townAddress: "Tangerang Selatan",
    roomDesc:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    roomCost: 9000000,
    roomSize: 1800,
    bedRoom: 5,
    bathRoom: 5,
    period: "Year",
  },
];

export default rooms;
